### ISSUE TITLE
It does not work perfectly like on codepen

### ISSUE THREAD

**Issue by murat** [juliangarnier/3D-Hartwig-chess-set#2]
I cant run this code. It does not work perfectly like on codepen. I downloaded this and run. 

Result :

![ekran alnts](https://f.cloud.github.com/assets/1137480/492784/9ad76ce4-baed-11e2-8ba9-7a3a447f2bec.jpg)

Why this might be happening?

Not : I didnt change any code. (Sorry for my bad english)

**Comment by juliangarnier** [comment]
It's because I use prefixfree (http://leaverou.github.io/prefixfree/). 
You have to put the game in a local server environment.

**Comment by murat** [comment]
Hey it works... Thanks for answer. :+1:  But dont exactly. That's my fault i know but i don't know how to solve this. Last result on server : 
![ekran alnts](https://f.cloud.github.com/assets/1137480/492934/8be301be-bb04-11e2-86c4-81770b1a5d6c.jpg)

**Comment by juliangarnier** [comment]
Sorry I don't really understand what you want to say. 
But I can't help you if you changed and broke something in the code. 
The issue was about running the game locally, and this was solved, so I close this issue.
